### ISSUE TITLE
Bug in club ark

### ISSUE THREAD

**Issue by tripack341** [Kexodus1/Ark-Ascended-Tools#1]
my character only jumps in the club ark mission and fail the mision every time, im playing in 1920x1080 thank you very much

**Comment by corsica2a0** [comment]
1/ Look ur bind key "C" for crouch.
2/ Test mouve ur gamma in game ( console: gamma 2.195 )

**Comment by Kexodus1** [comment]
Further adjusting of 1920x1080 in v4.1.0, seeing a 95% success rate now.  Will release tomorrow with addition of abberation.
