### ISSUE TITLE
Club ark coords and up

### ISSUE THREAD

**Issue by corsica2a0** [Kexodus1/Ark-Ascended-Tools#2]
Hello, in club ark is it possible to have an image to see where you selected the coordinates so that I can do it for my resolution and give them to you afterwards? I also suggest having a tolerance on the colors to avoid errors.

`#include <cmath>`

`MoveMouseUntilColorMatches(hdc, CAJC2X, CAJC2Y, RGB(255, 240, 0), 15);`

`while (!ColorMatches(GetPixel(hdc, CAJC1X, CAJC1Y), RGB(255, 255, 255), 15))`

**Comment by Kexodus1** [comment]
Thank you for bringing this to my attention.  I need to do more testing with this.  Currently is gamma is set to anything other than 2.2 it breaks a lot of the program functions.  I am looking at adding a gamma slider in settings or just adding tolerances to allow for a wider range of gamma settings.  Might take me a while to fully implement it.  In the meantime, I added the gamma values to troubleshooting so people will know gamma matters.

As for the coordinates in v4.1.0 I fully labeled the coordinates.cpp for easier coordinate additions in the future.  Hopefully with v4.0.4 all of the coordinates I added for your resolution function correctly.
