### ISSUE TITLE
For Azerty (MagicINI)

### ISSUE THREAD

**Issue by corsica2a0** [Kexodus1/Ark-Ascended-Tools#3]
Code MagicINI for keyboard Azerty ( my key for open console is ² )

`#include "pch.h"
#include "Features.h"
#include <windows.h>
#include <vector>

void SendKey(WORD vk, bool shift = false) {
    std::vector<INPUT> inputs(shift ? 4 : 2);

    if (shift) {
        inputs[0].type = INPUT_KEYBOARD;
        inputs[0].ki.wVk = VK_SHIFT;
        inputs[0].ki.dwFlags = 0;
        inputs[1].type = INPUT_KEYBOARD;
        inputs[1].ki.wVk = vk;
        inputs[1].ki.dwFlags = 0;
        inputs[2].type = INPUT_KEYBOARD;
        inputs[2].ki.wVk = vk;
        inputs[2].ki.dwFlags = KEYEVENTF_KEYUP;
        inputs[3].type = INPUT_KEYBOARD;
        inputs[3].ki.wVk = VK_SHIFT;
        inputs[3].ki.dwFlags = KEYEVENTF_KEYUP;
    }
    else {
        inputs[0].type = INPUT_KEYBOARD;
        inputs[0].ki.wVk = vk;
        inputs[0].ki.dwFlags = 0;
        inputs[1].type = INPUT_KEYBOARD;
        inputs[1].ki.wVk = vk;
        inputs[1].ki.dwFlags = KEYEVENTF_KEYUP;
    }
    SendInput(static_cast<UINT>(inputs.size()), inputs.data(), sizeof(INPUT));
}
void TypeCharacter(char ch) {
    SHORT vk = VkKeyScanA(ch);
    if (vk == -1) return; // Skip characters that can't be mapped

    bool shiftState = HIBYTE(vk) & 1;
    WORD vkKey = LOBYTE(vk);

    if (ch == '|') {
        // Simulate pressing AltGr (Ctrl + Alt) + 6 for "|"
        INPUT inputs[4] = {};
        inputs[0].type = INPUT_KEYBOARD;
        inputs[0].ki.wVk = VK_CONTROL;
        inputs[1].type = INPUT_KEYBOARD;
        inputs[1].ki.wVk = VK_MENU;
        inputs[2].type = INPUT_KEYBOARD;
        inputs[2].ki.wVk = '6';
        SendInput(3, inputs, sizeof(INPUT));

        inputs[0].ki.dwFlags = KEYEVENTF_KEYUP;
        inputs[1].ki.dwFlags = KEYEVENTF_KEYUP;
        inputs[2].ki.dwFlags = KEYEVENTF_KEYUP;
        SendInput(3, inputs, sizeof(INPUT));
    } else {
        SendKey(vkKey, shiftState);
    }
}
void TypeString(const char* str) {
    for (const char* p = str; *p; p++) 
    {
        if (*p == ' ') {
            SendKey(VK_SPACE);
        } else {
            TypeCharacter(*p);
        }
        Sleep(30); // Adjust delay to ensure each key press is registered
    }
}
void MagicINI()`

**Comment by Kexodus1** [comment]
Added AZERTY detection in v4.1.0, will release tomorrow with abberation.  Let me know on discord how it works, cannot test fully since I have QWERTY.
